### ISSUE TITLE
This is not a registered game setting

### ISSUE THREAD

**Issue by patrickmohrmann** [LeafWulf/weatherfx#5]
**Module Version:** v1.3.0

Console log

foundry.js:2758 Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: weatherfx]
    at ClientSettings.get (foundry.js:2758:42)
    at isChatOutputOn (weatherfx.js:179:43)
    at Object.onClick (weatherfx.js:143:25)
    at SceneControls._onClickTool (foundry.js:67163:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
**Describe the bug**

**To Reproduce**
toggle apply weather FX

**Expected behavior**
nothing happens on button click, but an error is shown in the log

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 
10.288

**Game System:** 
Earthdawn4e

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by paulo-roger** [comment]
Hi, thanks for the report!
Which version of Weather Control are you using?

**Comment by patrickmohrmann** [comment]
V4.1.9

**Comment by paulo-roger** [comment]
just released a fix, let me know if this works

**Comment by patrickmohrmann** [comment]
Now there are three errors

foundry.js:747 Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 2 packages: foundryvtt-simple-calendar, lib-wrapper]
    at SchemaField._validateType (commons.js:4090:15)
    at SchemaField.validate (commons.js:3817:37)
    at Setting.validate (commons.js:5470:35)
    at new DataModel (commons.js:5247:26)
    at new Document (commons.js:5786:3)
    at new BaseSetting (commons.js:9807:3)
    at new ClientDocumentMixin (foundry.js:12996:5)
    at new Setting (foundry.js:21232:1)
    at ClientSettings.get (foundry.js:2774:21)
    at $.LoadLeapYearRules (index.js:1:124617)
    at J.settingUpdate (index.js:1:180343)
    at J.LoadCalendars (index.js:1:174181)
    at ee.init (index.js:1:184198)
    at Object.fn (index.js:1:206850)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7767:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)

foundry.js:747 TypeError: Cannot read properties of undefined (reading 'api')
[Detected 2 packages: weather-control, foundryvtt-simple-calendar]
    at get SimpleCalendar [as SimpleCalendar] (weather-control.js:1:619)
    at n.timestamp (weather-control.js:1:896)
    at D.createDefaultWeatherData (weather-control.js:1:8356)
    at D.registerSettings (weather-control.js:1:7147)
    at new D (weather-control.js:1:5919)
    at weather-control.js:1:25925
    at Object.fn (weather-control.js:1:26381)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at j.emit (index.js:1:88748)
    at ee.primaryCheckTimeoutCall (index.js:1:184916)

foundry.js:2758 Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: weatherfx]
    at ClientSettings.get (foundry.js:2758:42)
    at getPrecipitation (weatherfx.js:92:43)
    at Object.onClick (weatherfx.js:142:31)
    at SceneControls._onClickTool (foundry.js:67163:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
get @ foundry.js:2758
getPrecipitation @ weatherfx.js:92
onClick @ weatherfx.js:142
_onClickTool @ foundry.js:67163
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
await in y.handle (async)
_onClickTool @ foundry.js:67163
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

the first two are popping up directly after starting the game or reload, the last one after clicking "apply Weather FX"

**Comment by paulo-roger** [comment]
Do you mind to debug this with me chatting in discord?

**Comment by patrickmohrmann** [comment]
sure, I have 25 minutes at least until my session starts tonight if that works for you 
patrickmohrmann#2953
